version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "3001:3001"
    networks:
      - app
  db:
    image: cassandra:4.0.6
    ports:
      - '9042:9042'
    volumes:
      - inmoitt-data:/var/lib/cassandra
    networks:
      - app
networks:
  app:
volumes:
  inmoitt-data:
    external: true