version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - "3001:3001"
    networks:
      - app
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app
networks:
  app:
volumes:
  mysql-data:
    external: true