version: '3.4'
services:
  api:
    build: ./
    ports:
      - "3001:3001"
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql
